import Navbar from "@/components/common/Navbar";
import "./globals.css";
import { Poppins } from "next/font/google";
import Footer from "@/components/common/Footer";

const poppins = Poppins({
  subsets: ["latin"],
  weight: ["100", "300", "400", "700", "800"],
});

export const metadata = {
  title: "CardFlex",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={poppins.className}>
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
